# Numpy
- Most used methods

In [4]:
import numpy as np

# Create Methods

In [108]:
example_arrays={}
example_arrays['array']=np.array([1,1,1,1])
example_arrays['zeros']=np.zeros(4)
example_arrays['ones']=np.ones(4)
example_arrays['identity']=np.eye(1)
example_arrays['random_int']=np.random.randint(1,4,size=(1,2))
example_arrays['random_float']=np.random.random((1,2))

for key,value in example_arrays.items():
    print(f"{key}: {value}")

array: [1 1 1 1]
zeros: [0. 0. 0. 0.]
ones: [1. 1. 1. 1.]
identity: [[1.]]
random_int: [[1 1]]
random_float: [[0.56780172 0.96773714]]


# Search methods

In [11]:
array=np.arange(5)[::-1]
example_arrays={}
example_arrays['array']=array
example_arrays['filter [array>2]']=array[array>2]
example_arrays['argmax']=np.argmax(array)
example_arrays['argmin']=np.argmin(array)
example_arrays['np.where_values']=np.where((array>1) & (array<4),array,0)

for key,value in example_arrays.items():
    print(f"{key}: {value}")

array: [4 3 2 1 0]
filter [array>2]: [4 3]
argmax: 0
argmin: 4
np.where: (array([0, 1, 2]),)
np.where_values: [0 3 2 0 0]


In [190]:
print("Broadcasting with np.where\n")
a = np.arange(12).reshape(3, 4)
b = np.arange(4).reshape(1, 4)

print('a:', a,'\n')
print('b', b,'\n')
# Broadcasts (a < 5, a, and b * 10)
# of shape (3, 4), (3, 4) and (1, 4)
c = np.where(a < 5, a, b * 10)

print('c:', c)

Broadcasting with np.where

a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

b [[0 1 2 3]] 

c: [[ 0  1  2  3]
 [ 4 10 20 30]
 [ 0 10 20 30]]


# Operations

In [243]:
array=np.array([[10.5,9.1],[0,0]])
example_arrays={}
example_arrays['array']=array
example_arrays['floor']=np.floor(array)
example_arrays['ceil']=np.ceil(array)
example_arrays['np.sum']=np.sum(array)
example_arrays['np.sum, axis=1']=np.sum(array,axis=1)
example_arrays['np.delete, axis=1']=np.delete(array,obj=1,axis=1)

# example_arrays['np.where_values']=np.where((array>1) & (array<4),array,0)

for key,value in example_arrays.items():
    print(f"{key}: {value}")

array: [[10.5  9.1]
 [ 0.   0. ]]
floor: [[10.  9.]
 [ 0.  0.]]
ceil: [[11. 10.]
 [ 0.  0.]]
np.sum: 19.6
np.sum, axis=1: [19.6  0. ]
np.delete, axis=1: [[10.5]
 [ 0. ]]


# Broadcasting

In [221]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
y = np.array([1, 0, 1])
example_arrays={}
example_arrays['x']=x
example_arrays['y']=y
example_arrays['x+y']=x+y
for key,value in example_arrays.items():
    print(f"{key}: {value}\n")

x: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

y: [1 0 1]

x+y: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]



# Matrix operations
- operations are element wise
- np.dot ==np.matmul (advised to use matmul for dimension>1)

In [216]:
x=np.array([2,2,2])
y=np.array([3,3,3])
example_arrays={}
example_arrays['x']=x
example_arrays['y']=y
example_arrays['x+y']=x+y
example_arrays['x**2']=x**2

for key,value in example_arrays.items():
    print(f"{key}: {value}")

x: [2 2 2]
y: [3 3 3]
x+y: [5 5 5]
x**2: [4 4 4]
np.dot(x,y): 18
np.matmul(x,y): 18


In [218]:
x=np.array([[2,2,2],[2,2,2]])
y=np.array([3,3,3])
example_arrays={}
example_arrays['x']=x
example_arrays['y']=y
example_arrays['np.matmul(x,y)']=np.matmul(x,y)
for key,value in example_arrays.items():
    print(f"{key}: {value}")

x: [[2 2 2]
 [2 2 2]]
y: [3 3 3]
np.matmul(x,y): [18 18]


# Sorting methods

In [249]:
x = np.array([[12,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
np.sort(x,axis=0)
np.argsort(x)
example_arrays={}
example_arrays['x']=x
example_arrays['np.sort,axis=0']=np.sort(x,axis=0)
example_arrays['np.argsort,axis=0']=np.argsort(x,axis=0)

for key,value in example_arrays.items():
    print(f"{key}: {value}")

x: [[12  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
np.sort,axis=0: [[ 4  2  3]
 [ 7  5  6]
 [10  8  9]
 [12 11 12]]
np.argsort,axis=0: [[1 0 0]
 [2 1 1]
 [3 2 2]
 [0 3 3]]


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = a > 5
# Get elements greater than 5 with dimensions
a[mask]
print(a[mask])

[6 7 8 9]


In [10]:
len(a[a>5])

4